### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by Rhaegar121** [Rhaegar121/React-Group-Project#25]
In this issue, we have completed the following tasks.

1. we have created the kanban project board. The link is here - https://github.com/Rhaegar121/React-Group-Project/projects/1
2. There are 2 people on our project team.
3. Achieved all cards with team 3 in the title.
4. Assigned all team members to the cards from all categories

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
